export enum CaseStatus {
  STATUS_00_DRAFT = 'STATUS_00_DRAFT',
  STATUS_01_PENDING_CASE_CREATION_APPROVAL = 'STATUS_01_PENDING_CASE_CREATION_APPROVAL',
  STATUS_02_READY_FOR_ASSIGNMENT = 'STATUS_02_READY_FOR_ASSIGNMENT',
  STATUS_03_RETURNED = 'STATUS_03_RETURNED',
  STATUS_10_ASSIGNED = 'STATUS_10_ASSIGNED',
  STATUS_20_IN_PROGRESS = 'STATUS_20_IN_PROGRESS',
  STATUS_21_SUSPENDED = 'STATUS_21_SUSPENDED',
  STATUS_22_PENDING_FINAL_APPROVAL = 'STATUS_22_PENDING_FINAL_APPROVAL',
  STATUS_30_PENDING_REOPENING = 'STATUS_30_PENDING_REOPENING',
  STATUS_31_REOPENED = 'STATUS_31_REOPENED',
  STATUS_71_AUTOCLOSED_CONFIRMED = 'STATUS_71_AUTOCLOSED_CONFIRMED',
  STATUS_72_AUTOCLOSED_REFUTED = 'STATUS_72_AUTOCLOSED_REFUTED',
  STATUS_81_CLOSED_REFUTED = 'STATUS_81_CLOSED_REFUTED',
  STATUS_82_CLOSED_CONFIRMED = 'STATUS_82_CLOSED_CONFIRMED',
  STATUS_83_CLOSED_INCONCLUSIVE = 'STATUS_83_CLOSED_INCONCLUSIVE',
  STATUS_99_ABANDONED = 'STATUS_99_ABANDONED',
}
export enum Priority {
  NEW = 'NEW',
  URGENT = 'URGENT',
  CRITICAL = 'CRITICAL',
  BREACH = 'BREACH',
}
export enum CaseType {
  FRAUD = 'FRAUD',
  AML = 'AML',
  FRAUD_AND_AML = 'FRAUD_AND_AML',
  NONE = 'NONE',
}
export enum CaseCreationType {
  MANUAL = 'MANUAL',
  AUTOMATIC_SYSTEM = 'AUTOMATIC_SYSTEM',
}
import { IsEnum, IsOptional, IsString, IsUUID } from 'class-validator';

export class CreateCaseDto {
  @IsUUID()
  @IsOptional()
  parentId?: string;

  @IsString()
  tenantId: string;

  @IsUUID()
  caseCreatorUserId: string;

  @IsUUID()
  caseOwnerUserId: string;

  @IsEnum(CaseStatus)
  status: CaseStatus;

  @IsEnum(Priority)
  priority: Priority;

  @IsEnum(CaseType)
  @IsOptional()
  caseType?: CaseType;

  @IsEnum(CaseCreationType)
  caseCreationType: CaseCreationType;
}
