export enum CaseClosureOutcome {
  CLOSED_REFUTED = 'STATUS_81_CLOSED_REFUTED',
  CLOSED_CONFIRMED = 'STATUS_82_CLOSED_CONFIRMED',
  CLOSED_INCONCLUSIVE = 'STATUS_83_CLOSED_INCONCLUSIVE',
  COMPLETE = 'STATUS_84_COMPLETED',
}
