export const getCaseStatusBadge = (status: string): string => {
  const statusMap = {
    STATUS_00_DRAFT: '00_DRAFT',
    STATUS_10_ASSIGNED: '10_ASSIGNED',
    STATUS_20_IN_PROGRESS: '20_IN_PROGRESS',
    STATUS_21_SUSPENDED: '21_SUSPENDED',
    STATUS_22_PENDING_FINAL_APPROVAL: '22_PENDING_FINAL_APPROVAL',
    STATUS_30_COMPLETED: '30_COMPLETED',
    STATUS_31_PENDING_CASE_REOPENING_APPROVAL:
      '31_PENDING_CASE_REOPENING_APPROVAL',
    STATUS_81_CLOSED_REFUTED: '81_CLOSED_REFUTED',
    STATUS_82_CLOSED_CONFIRMED: '82_CLOSED_CONFIRMED',
    STATUS_83_CLOSED_INCONCLUSIVE: '83_CLOSED_INCONCLUSIVE',
    STATUS_99_ABANDONED: '99_ABANDONED',
    STATUS_02_READY_FOR_ASSIGNMENT: '02_READY_FOR_ASSIGNMENT',
    STATUS_01_PENDING_CASE_CREATION_APPROVAL:
      '01_PENDING_CASE_CREATION_APPROVAL',
  } as const;
  return statusMap[status as keyof typeof statusMap] || status;
};
