-- Reassign any remaining STATUS_84_COMPLETED rows before the value is dropped.
UPDATE "cases" SET "status" = 'STATUS_83_CLOSED_INCONCLUSIVE' WHERE "status" = 'STATUS_84_COMPLETED';
UPDATE "cases" SET "final_outcome" = 'STATUS_83_CLOSED_INCONCLUSIVE' WHERE "final_outcome" = 'STATUS_84_COMPLETED';

-- AlterEnum
ALTER TYPE "CaseStatus" RENAME TO "CaseStatus_old";

CREATE TYPE "CaseStatus" AS ENUM ('STATUS_00_DRAFT', 'STATUS_01_PENDING_CASE_CREATION_APPROVAL', 'STATUS_02_READY_FOR_ASSIGNMENT', 'STATUS_03_RETURNED', 'STATUS_10_ASSIGNED', 'STATUS_20_IN_PROGRESS', 'STATUS_21_SUSPENDED', 'STATUS_22_PENDING_FINAL_APPROVAL', 'STATUS_31_PENDING_CASE_REOPENING_APPROVAL', 'STATUS_71_AUTOCLOSED_CONFIRMED', 'STATUS_72_AUTOCLOSED_REFUTED', 'STATUS_81_CLOSED_REFUTED', 'STATUS_82_CLOSED_CONFIRMED', 'STATUS_83_CLOSED_INCONCLUSIVE', 'STATUS_99_ABANDONED');

ALTER TABLE "cases" ALTER COLUMN "status" TYPE "CaseStatus" USING ("status"::text::"CaseStatus");
ALTER TABLE "cases" ALTER COLUMN "final_outcome" TYPE "CaseStatus" USING ("final_outcome"::text::"CaseStatus");

DROP TYPE "CaseStatus_old";
