import { ApiProperty } from '@nestjs/swagger';

export class AlertDetailsDto {
  @ApiProperty({ description: 'Unique Identifier for the alert' })
  alertId: string;

  @ApiProperty({ description: 'Severity classification (e.g., HIGH, MEDIUM, LOW)' })
  riskLevel: string;

  @ApiProperty({ description: 'Raw score generated by the logic engine' })
  typologyScore: number;

  @ApiProperty({ description: 'Whether the transaction was automatically blocked' })
  isInterdiction: boolean;

  @ApiProperty({ description: 'Date of the alert (YYYY-MM-DD)' })
  alertDate: string;

  @ApiProperty({ description: 'Tenant identifier', required: false })
  tenantId?: string;

  @ApiProperty({ description: 'Additional alert data', required: false })
  additionalData?: Record<string, any>;
}
